version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=typing_game_dev
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
